name: packages-cok-community-docker

on:
  workflow_run:
    workflows: ["toolchain-turris-cok-sdk"]
    branches: [master]
    types: [completed]
  push:
    branches: [ master ]
    paths: [".github/workflows/packages-cok-community-docker.yml"]
  pull_request:
    branches: [ master ]
    paths: [".github/workflows/packages-cok-community-docker.yml"]

jobs:
  ci:
    strategy:
      matrix:
        device: [omnia]
        tag: [stable, latest]
    runs-on: ubuntu-latest
    container: selwtf/turris-cok-sdk:${{ matrix.device }}-${{ matrix.tag }}
    steps:
      - name: "Fetch openwrt community packages @master"
        run: git clone https://github.com/openwrt/packages.git /workspace/pkgs

      - name: "Build docker"
        run: /build.sh package docker

      - name: "Store artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.device }}-${{ matrix.tag }}-community-docker
          path: /workspace/artifacts

  deploy:
    needs: ci
    strategy:
      matrix:
        device: [omnia]
        tag: [stable, latest]
    runs-on: ubuntu-latest
    container: selwtf/deploy-pkg-repo:v0.0.1
    steps:
    - name: "Checkout git repository"
      uses: actions/checkout@v2

    - name: "Prepare secrets"
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase=$SECRET_KEY --output /gsutil/service-account.json .secrets/gcp-sa.json.enc && chmod 600 /gsutil/service-account.json
        gpg --quiet --batch --yes --decrypt --passphrase=$SECRET_KEY --output /sign.key .secrets/sign.key.enc && chmod 600 /sign.key
      env:
        SECRET_KEY: ${{ secrets.CI_SECRET_KEY }}

    - name: "Download docker artifacts"
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.device }}-${{ matrix.tag }}-community-docker
        path: /workspace/new
        
    - name: "Deploy new packages and update public repo"
      run: /pkg-repo.sh
      env:
        GCS_BUCKET: sel-wtf-turris/${{ matrix.device }}/cok/${{ matrix.tag }}/packages
      